### ISSUE TITLE
Questions related to ichrome_user_data

### ISSUE THREAD

**Issue by juanfrilla** [ClericPy/ichrome#138]
1. Why ichrome is generating data in the ichrome_user_data folder?
2. Can it be deleted or any option to delete after every execution? 
3. Is there any option to deactivate it? It takes a lot of space from the disk.

Here its a screenshot:
![Captura de pantalla 2023-09-21 a las 9 16 04](https://github.com/ClericPy/ichrome/assets/38920780/c31efc80-da8d-4633-ab3b-754b515b29ac)

**Comment by ClericPy** [comment]
When the chrome process starts, it relies on a user directory to distinguish different contexts, so a directory will be created every time. In order to distinguish the process, ichrome will generate a different directory for each port number for isolation.

Back to the question you asked,

1. avoid generating user dir This cannot be done with a directory, but you can set a custom directory for storage with `user_data_dir="./somedir"` to replace the default home directory.
2. `clear_after_shutdown=True,` to auto clear user dir after shutdowning chrome daemon
3. use `incognito_tab` method for concurrency usage, if you use multiple ports for chrome daemons with proxies.

PS: why you use so many different port here?

**Comment by juanfrilla** [comment]
Thanks @ClericPy, i'll use `clear_after_shutdown=True`
I use different ports because I'm using different scrapy spiders at the same time (https://github.com/ClericPy/ichrome/issues/131)
But I think I'm going to use a shared browser (https://github.com/ClericPy/ichrome/issues/129) to have only one opened browser and all the spiders conect to that browser
