### ISSUE TITLE
How to add extension and add proxy authentication in ichrome ?

### ISSUE THREAD

**Issue by tuan-newmoon** [ClericPy/ichrome#41]
Hello, I have a question about how to add extension and proxy authentication ? I hope someone will help me out: D

In selenium, i will write 1 extension to add proxy authen but ichrome, i can't find to add it :(

**Comment by ClericPy** [comment]
1. I have not tried extensions before, but you can install them in headless=False mode, and copy the user data dir to target location. Because extensions is in there by default.
2. `proxy authentication` is now allowed by default chromium, I tried to use gost for the `Forward proxy authentication
`
https://github.com/ginuerzh/gost/blob/master/README_en.md

**Comment by ClericPy** [comment]
auth proxy issue https://github.com/ClericPy/ichrome/issues/86
