### ISSUE TITLE
how to selectall?

### ISSUE THREAD

**Issue by snja** [ClericPy/ichrome#45]
`keyboard_send(type="rawKeyDown", key="Control+a")`

this code is wrong

**Comment by ClericPy** [comment]
Because `select all` is actually a system operation, and ichrome relies on the operation done by the Chrome CDP protocol. The latter is only a subset of the Devtools that we usually call when using the browser, and the shortcut key behavior actually depends on the dispatch keyboard and mouse events To do it.
If you can, please tell me what you want to do after selecting all, let me see if there is a way to achieve it through JS.
https://chromedevtools.github.io/devtools-protocol/

So, try some Javascript ways to do what you want
